--- #YAML:1.0
name:               mojolicious-lexicon
version:            0.9
abstract:           ~
author:
    - Sergey Zasenko <undef@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:   0
    Mojolicious:  1.0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
