---
abstract: unknown
author:
  - 'Sergey Zasenko <undef@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: mojolicious-lexicon
no_index:
  directory:
    - t
    - inc
requires:
  File::Find: 0
  Getopt::Long: 0
  Mojolicious: 1.0
version: 0.9922
